apiVersion: v1
kind: ConfigMap
metadata:
  name: cloud-notes-config
  namespace: cloud-notes
data:
  ENVIRONMENT: production
  PORT: "5000"
  CACHE_TTL_SECONDS: "120"
  AWS_REGION: ap-southeast-1
  KAFKA_TOPIC: cloud-notes.events
