apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: cloud-notes-gateway
  namespace: cloud-notes
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      tls:
        httpsRedirect: true
      hosts:
        - "khanhhoang.page"
    - port:
        number: 80
        name: http-wildcard
        protocol: HTTP
      hosts:
        - "*"
    - port:
        number: 443
        name: https
        protocol: HTTPS
      tls:
        mode: SIMPLE
        credentialName: khanhhoang-page-tls
      hosts:
        - "khanhhoang.page"
