apiVersion: v1
kind: Secret
metadata:
  name: cloud-notes-secrets
  namespace: cloud-notes
type: Opaque
stringData:
  DATABASE_URL: postgresql+psycopg://cloudnotes:CHANGE_ME@cloud-notes-postgres.abcdefghijkl.ap-southeast-1.rds.amazonaws.com:5432/cloudnotes
  REDIS_URL: redis://cloud-notes-redis.xxxxxx.ng.0001.aps1.cache.amazonaws.com:6379/0
  KAFKA_BOOTSTRAP_SERVERS: b-1.cloud-notes.abcde.c2.kafka.ap-southeast-1.amazonaws.com:9092
  AWS_ACCESS_KEY_ID: CHANGE_ME
  AWS_SECRET_ACCESS_KEY: CHANGE_ME
  AWS_BUCKET_NAME: your-s3-bucket
  AWS_REGION: ap-southeast-1
  S3_ENDPOINT_URL: ""
  S3_PUBLIC_BASE_URL: ""
